name: Rust on Arch Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm rustup
          rustup default stable
          rustup update

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
